### ISSUE TITLE
No Realm on List in Client

### ISSUE THREAD

**Issue by GhaleonZ** [JunkyBulgaria/BlizzlikeRepack-5.4#12]
Downloaded a fresh copy of this from AC Web, along with the Client.

Loaded up the server on my Laptop. Used Heidi to go in and set Address to 192.168.0.100 because that is the IP of my Laptop on the home network.

I ran the client on my desktop and it connected me to the account I registered in the World Server very easily.
Then it asked me to search for a realm. I used Developmental and Normal because that is what is listed in the World Server conf file.

Nothing is displayed. Nothing has been edited beyond the Address column under Realm List in the database. The rest is exactly as downloaded.

**Comment by FALL1N1** [comment]
use the provided wow.exe
